--- #YAML:1.0
name:               Math-Int64-C_API-Sample
version:            0.03
abstract:           ~
author:
    - Eto Demerzel <eto.demerzel@usrobots.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Math::Int64:  0.16
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
